/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minimarket;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quinquee
 */
public class form_barang extends javax.swing.JFrame {

    /**
     * Creates new form form_barang
     */
    public form_barang() {
        initComponents();
        koneksi_database();
        text_empty();
        AutoNumber();
        view_barang("SELECT * FROM barang");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JButton();
        pencarian = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_barang = new javax.swing.JTable();
        cmb_cari = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        input_kode = new javax.swing.JTextField();
        input_nama = new javax.swing.JTextField();
        input_harga_pokok = new javax.swing.JTextField();
        input_harga_jual = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        input_stok = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmb_satuan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Form Entry Data Barang");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        btn_keluar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_keluar.setText("KELUAR");
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 90, 40));

        pencarian.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pencarian.setText("Cari");
        jPanel1.add(pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 170, -1));

        list_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        list_barang.setRowHeight(22);
        jScrollPane1.setViewportView(list_barang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 660, 130));

        cmb_cari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Barang", "Nama Barang" }));
        cmb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cariActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 120, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Filter");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Kode Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Nama Barang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Satuan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Harga Pokok");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Harga Jual");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText(":");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 10, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText(":");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 10, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 10, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 10, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText(":");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 10, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText(":");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 10, -1));

        input_kode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        input_kode.setText("Input Kode");
        input_kode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_kodeKeyPressed(evt);
            }
        });
        jPanel1.add(input_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 170, -1));

        input_nama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        input_nama.setText("Input Nama");
        jPanel1.add(input_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 260, -1));

        input_harga_pokok.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        input_harga_pokok.setText("Input Harga Pokok");
        input_harga_pokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_harga_pokokActionPerformed(evt);
            }
        });
        jPanel1.add(input_harga_pokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, -1));

        input_harga_jual.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        input_harga_jual.setText("Input Harga Jual");
        input_harga_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_harga_jualActionPerformed(evt);
            }
        });
        jPanel1.add(input_harga_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 170, -1));

        btn_simpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 80, 40));

        btn_cancel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 90, 40));

        btn_edit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 90, 40));

        btn_hapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_hapus.setText("HAPUS");
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 90, 40));

        input_stok.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        input_stok.setText("Input Stok");
        jPanel1.add(input_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 170, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Stok");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        cmb_satuan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Satuan-", "Buah", "Unit", "Kg", "Bungkus", "Dus", "Pcs", "Lembar" }));
        cmb_satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_satuanActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        try {
            sql = "INSERT INTO barang VALUES ('"+input_kode.getText()+
                    "','"+input_nama.getText()+
                    "','"+cmb_satuan.getSelectedItem()+
                    "','"+input_harga_pokok.getText()+
                    "','"+input_harga_jual.getText()+
                    "','"+input_stok.getText()+
                    "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Tersimpan.....");
            text_empty();
            AutoNumber();
            stat.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal....." + e);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void input_harga_pokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_harga_pokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_harga_pokokActionPerformed

    private void cmb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cariActionPerformed

    private void input_harga_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_harga_jualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_harga_jualActionPerformed

    private void input_kodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_kodeKeyPressed
       //check code for button enter = 10
       if(evt.getKeyCode()==10 && input_kode.getText().equalsIgnoreCase("")==false){
           view_data();
       }else{
           text_empty();
       }
    }//GEN-LAST:event_input_kodeKeyPressed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            sql = "UPDATE barang SET nama_barang='"+input_nama.getText()+
                    "',satuan='"+cmb_satuan.getSelectedItem()+
                    "',harga_pokok='"+input_harga_pokok.getText()+
                    "',harga_jual='"+input_harga_jual.getText()+
                    "',stok='"+input_stok.getText()+
                    "' WHERE kode_barang='"+input_kode.getText()+"'";
            stat =  con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Sukses Diedit....");
            text_empty();
            AutoNumber();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal...."+e);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void cmb_satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_satuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_satuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JComboBox<String> cmb_satuan;
    private javax.swing.JTextField input_harga_jual;
    private javax.swing.JTextField input_harga_pokok;
    private javax.swing.JTextField input_kode;
    private javax.swing.JTextField input_nama;
    private javax.swing.JTextField input_stok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable list_barang;
    private javax.swing.JTextField pencarian;
    // End of variables declaration//GEN-END:variables

private Connection con;
private Statement stat;
private ResultSet rs;
private String sql;

private void koneksi_database(){
   try {
       Class.forName("com.mysql.jdbc.Driver");
       System.out.println("Driver Ditemukan...");
       try {
           String url = "jdbc:mysql://localhost:3306/minimarket?user=root&password=";
           con = DriverManager.getConnection(url);
           System.out.println("Terkoneksi.....");
           
       } catch (SQLException e){
           System.err.println("Tidak Terkoneksi.....");
       }
   } catch (ClassNotFoundException e){
       System.err.println("Driver Tidak Ditemukan.......");
   }
}

private void text_empty(){
    input_nama.setText("");
    cmb_satuan.setSelectedIndex(0);
    input_harga_pokok.setText("");
    input_harga_jual.setText("");
    input_stok.setText("");
    pencarian.setText("");
    input_kode.requestFocus();
}

private void AutoNumber(){
    try {
        sql = "SELECT MAX(RIGHT(kode_barang,4)) AS no_auto FROM barang";
        stat = con.createStatement();
        rs = stat.executeQuery(sql);
        if(rs.next()){
            String no_auto, nol_plus;
            int p;
            no_auto = Integer.toString(rs.getInt(1)+1);
            p = no_auto.length();
            nol_plus ="";
            for(int i=1; i<=4-1; i++){
            nol_plus = nol_plus+"0";
            }
            input_kode.setText("B"+nol_plus+no_auto);    
        }
            
    } catch (Exception e) {
        input_kode.setText("B0001");
    } 
}

private void view_data(){
    try {
        sql = "SELECT * FROM barang WHERE kode_barang='"+input_kode.getText()+"'";
        stat = con.createStatement();
        rs = stat.executeQuery(sql);
        if(rs.next()){
            input_nama.setText(rs.getString("nama_barang"));
            cmb_satuan.setSelectedItem(rs.getString("satuan"));
            input_harga_pokok.setText(rs.getString("harga_pokok"));
            input_harga_jual.setText(rs.getString("harga_jual"));
            input_stok.setText(rs.getString("stok"));
        }
    } catch (Exception e) {
    }
}


private void view_barang (String sql){
Object[] header = {"No","Kode","Nama Barang","Satuan","Harga Pokok","Harga Jual","Stok"};
DefaultTableModel tabel = new DefaultTableModel(null, header);
list_barang.setModel(tabel);
try {
  stat = con.createStatement();
  rs = stat.executeQuery(sql);
  byte no = 1;
  while (rs.next()){
  String[] Data = {
      Byte.toString(no),
      rs.getString("kode_barang"),
      rs.getString("nama_barang"),
      rs.getString("satuan"),
      rs.getString("harga_pokok"),
      rs.getString("harga_jual"),
      rs.getString("stok")
  };  
  tabel.addRow(Data);
  no++;
  }
  list_barang.getColumnModel().getColumn(0).setPreferredWidth(30);
  list_barang.getColumnModel().getColumn(1).setPreferredWidth(50);
  list_barang.getColumnModel().getColumn(2).setPreferredWidth(200);
} catch (Exception e) {
  System.err.println (e);
}
}

}
